In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
df = pd.read_csv('../data/postings.csv')

print("Shape:", df.shape)
print("\nColumns:\n", df.columns.tolist())

Shape: (123849, 31)

Columns:
 ['job_id', 'company_name', 'title', 'description', 'max_salary', 'pay_period', 'location', 'company_id', 'views', 'med_salary', 'min_salary', 'formatted_work_type', 'applies', 'original_listed_time', 'remote_allowed', 'job_posting_url', 'application_url', 'application_type', 'expiry', 'closed_time', 'formatted_experience_level', 'skills_desc', 'listed_time', 'posting_domain', 'sponsored', 'work_type', 'currency', 'compensation_type', 'normalized_salary', 'zip_code', 'fips']

In [2]:
df.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  object
 2   title                       123849 non-null  object
 3   description                 123842 non-null  object
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   object
 6   location                    123849 non-null  object
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  object
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              15246 non-null   float64
 15  job_posting_url             123849 non-null  object
 16  application_url             87184 non-null   object
 17  application_type            123849 non-null  object
 18  expiry                      123849 non-null  float64
 19  closed_time                 1073 non-null    float64
 20  formatted_experience_level  94440 non-null   object
 21  skills_desc                 2439 non-null    object
 22  listed_time                 123849 non-null  float64
 23  posting_domain              83881 non-null   object
 24  sponsored                   123849 non-null  int64
 25  work_type                   123849 non-null  object
 26  currency                    36073 non-null   object
 27  compensation_type           36073 non-null   object
 28  normalized_salary           36073 non-null   float64
 29  zip_code                    102977 non-null  float64
 30  fips                        96434 non-null   float64
dtypes: float64(14), int64(2), object(15)
memory usage: 29.3+ MB

In [4]:
# الأعمدة المهمة بس
cols = [
    'job_id', 'title', 'company_name', 'location',
    'formatted_work_type', 'formatted_experience_level',
    'normalized_salary', 'pay_period', 'remote_allowed'
]

df_clean = df[cols].copy()

print("Shape:", df_clean.shape)
df_clean.head()

Shape: (123849, 9)

,job_id,title,company_name,location,formatted_work_type,formatted_experience_level,normalized_salary,pay_period,remote_allowed
0,921716,Marketing Coordinator,Corcoran Sawyer Smith,"Princeton, NJ",Full-time,NaN,38480.0,HOURLY,NaN
1,1829192,Mental Health Therapist/Counselor,NaN,"Fort Collins, CO",Full-time,NaN,83200.0,HOURLY,NaN
2,10998357,Assitant Restaurant Manager,The National Exemplar,"Cincinnati, OH",Full-time,NaN,55000.0,YEARLY,NaN
3,23221523,Senior Elder Law / Trusts and Estates Associat...,"Abrams Fensterman, LLP","New Hyde Park, NY",Full-time,NaN,157500.0,YEARLY,NaN
4,35982263,Service Technician,NaN,"Burlington, IA",Full-time,NaN,70000.0,YEARLY,NaN

In [5]:
# تحميل ملفات الـ skills
df_job_skills = pd.read_csv('../data/job_skills.csv')
df_skills_map = pd.read_csv('../data/skills.csv')

print("Job Skills Shape:", df_job_skills.shape)
print("\nJob Skills Sample:")
print(df_job_skills.head())

print("\nSkills Map Sample:")
print(df_skills_map.head())

Job Skills Shape: (213768, 2)

Job Skills Sample:
       job_id skill_abr
0  3884428798      MRKT
1  3884428798        PR
2  3884428798       WRT
3  3887473071      SALE
4  3887465684       FIN

Skills Map Sample:
  skill_abr          skill_name
0       ART        Art/Creative
1      DSGN              Design
2      ADVR         Advertising
3      PRDM  Product Management
4      DIST        Distribution

In [6]:
df_job_skills_named = df_job_skills.merge(df_skills_map, on='skill_abr', how='left')

df_full = df_clean.merge(df_job_skills_named, on='job_id', how='left')

print("Shape:", df_full.shape)
print("\nSample:")
df_full.head(10)

Shape: (207531, 11)

Sample:

,job_id,title,company_name,location,formatted_work_type,formatted_experience_level,normalized_salary,pay_period,remote_allowed,skill_abr,skill_name
0,921716,Marketing Coordinator,Corcoran Sawyer Smith,"Princeton, NJ",Full-time,NaN,38480.0,HOURLY,NaN,MRKT,Marketing
1,921716,Marketing Coordinator,Corcoran Sawyer Smith,"Princeton, NJ",Full-time,NaN,38480.0,HOURLY,NaN,SALE,Sales
2,1829192,Mental Health Therapist/Counselor,NaN,"Fort Collins, CO",Full-time,NaN,83200.0,HOURLY,NaN,HCPR,Health Care Provider
3,10998357,Assitant Restaurant Manager,The National Exemplar,"Cincinnati, OH",Full-time,NaN,55000.0,YEARLY,NaN,MGMT,Management
4,10998357,Assitant Restaurant Manager,The National Exemplar,"Cincinnati, OH",Full-time,NaN,55000.0,YEARLY,NaN,MNFC,Manufacturing
5,23221523,Senior Elder Law / Trusts and Estates Associat...,"Abrams Fensterman, LLP","New Hyde Park, NY",Full-time,NaN,157500.0,YEARLY,NaN,OTHR,Other
6,35982263,Service Technician,NaN,"Burlington, IA",Full-time,NaN,70000.0,YEARLY,NaN,IT,Information Technology
7,91700727,Economic Development and Planning Intern,Downtown Raleigh Alliance,"Raleigh, NC",Internship,NaN,35360.0,HOURLY,NaN,PRJM,Project Management
8,103254301,Producer,Raw Cereal,United States,Contract,NaN,180000.0,YEARLY,1.0,DSGN,Design
9,103254301,Producer,Raw Cereal,United States,Contract,NaN,180000.0,YEARLY,1.0,ART,Art/Creative

In [8]:

df_full.to_csv('../output/jobs_clean.csv', index=False)
df_clean.to_csv('../output/jobs_main.csv', index=False)

print("✅ Saved")
print(f"jobs_clean.csv  → {df_full.shape[0]:,} rows")
print(f"jobs_main.csv   → {df_clean.shape[0]:,} rows")

✅ Saved
jobs_clean.csv  → 207,531 rows
jobs_main.csv   → 123,849 rows